name: Daily Python Script and GitHub Pages Build

on:
  schedule:
    - cron: '0 6 * * *'  # 6 AM UTC every day
  workflow_dispatch:  # Allows manual execution

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Python Script
        run: python main.py

      - name: Upload HTTP Response as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: http-response
          path: response.html
          retention-days: 7

      - name: Trigger GitHub Pages Build
        if: success()  # Only trigger if the script succeeds
        run: gh workflow run update-gh-pages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
