name: daily-update

on:
  schedule:
    - cron: '0 6 * * *'  # 6 AM UTC every day

  workflow_dispatch:  # Allows manual execution

permissions:
  contents: write  # Give permission to push changes

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: production
    env:
      JPDB_SID: ${{ secrets.JPDB_SID }}
      ENV: ${{ vars.ENV }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: '${{ github.head_ref }}'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Python Script
        run: python main.py

      - name: Commit and Push Datapoint
        if: success()
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add gh-page/datapoints.txt
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update datapoints.txt [CI]"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload HTTP Response as Artifact
        if: failure()
        run: |
          if [ -f response.html ]; then
            echo "Uploading response.html..."
            gh run upload-artifact --name http-response --retention-days 7 response.html
          else
            echo "No response.html file found. Skipping upload."
          fi
